name: metar_dbt
version: '1.0'
config-version: 2

profile: metar_profile

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  metar_dbt:
    +schema: "{{ env_var('DBT_SCHEMA','analytics') }}"
    stg:
      +tags: ["stg"]
    ods:
      +tags: ["ods"]
    dwh:
      +tags: ["dwh", "marts"]

  elementary:
    +schema: "elementary"
    +tags: ["elementary"]