version: 2

models:
  - name: ods_metar_latest
    description: "ODS слой (история) с METAR-наблюдениями после очистки STG"
    tags: ["ods", "metar"]

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ["icao", "observed", "id"]

    columns:
      - name: id
        description: "Идентификатор записи (Mongo ObjectId в виде строки)"
        tests:
          - not_null

      - name: icao
        description: "Идентификатор аэропорта (ICAO)"
        tests:
          - not_null

      - name: observed
        description: "Время наблюдения"
        tests:
          - not_null
